sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-contrib-9.3

services:
  - postgresql

language: python

python:
  - "2.7"

cache: pip

git:
  submodules: false

before_install:
  # Access the submodule via https instead of default SSH
  - git config submodule.core.url https://github.com/NYPL-Simplified/server_core.git
  - git submodule update --init --recursive

install:
  # pycparser is a dependency of cairosvg that currently does not work on travis.
  # The bug has apparently been fixed (https://github.com/eliben/pycparser/issues/148)
  # but it still doesn't work with cairocffi: https://github.com/Kozea/cairocffi/issues/91
  # This is a temporary workaround.
  - pip install git+https://github.com/eliben/pycparser@release_v2.14
  - pip install -r requirements.txt
  - python -m textblob.download_corpora

before_script:
  - psql -c 'create user simplified_test;' -U postgres
  - psql -c 'create database simplified_circulation_test;' -U postgres
  - psql -c 'grant all privileges on database simplified_circulation_test to simplified_test;' -U postgres

env:
 - SIMPLIFIED_TEST_DATABASE="postgres://simplified_test:test@localhost:5432/simplified_circulation_test"

script: ./verbose-test
